### ISSUE TITLE
Support Nougat

### ISSUE THREAD

**Issue by joaoevangelista** [ParkSangGwon/TedBottomPicker#10]
Since API 24 we can't expose a file using file:// scheme, because it will cause `android.os.FileUriExposedException`, since `StrictMode` was enhanced for this since this version.

We need change the scheme to other one, maybe `content`?

Here is the [particular line](https://github.com/ParkSangGwon/TedBottomPicker/blob/master/tedbottompicker/src/main/java/gun0912/tedbottompicker/TedBottomPicker.java#L221) where the exception happens .

[Here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en) is more info.

**Comment by ParkSangGwon** [comment]
@joaoevangelista Oh.. I will review about nougat file uri issue. Thnanks.

**Comment by rohitshampur** [comment]
Added support please accept the pull request https://github.com/rohitshampur/TedBottomPicker

**Comment by StephenMilone** [comment]
Would love to use this lib in a new project I'm working on. But this is a deal breaker. Please update. thank you

**Comment by majidkabir** [comment]
Please update, this is a big problem in Nougat, and don't work on it!

**Comment by ParkSangGwon** [comment]
@rohitshampur @StephenMilone @majidkabir 
Thanks to @rohitshampur
Support Nougat version updated
