### ISSUE TITLE
Why apply button is invisible?

### ISSUE THREAD

**Issue by pavelv99** [ParkSangGwon/TedBottomPicker#103]
<b>Why button is invisible? Although the view is exist(look at bounds)… 
Thanks in advance.</b>

<img src="https://pp.userapi.com/c850132/v850132162/28a3b/6QFi4XtuB6E.jpg">

**Comment by ParkSangGwon** [comment]
@pavelv99 
Please show your code

**Comment by ParkSangGwon** [comment]
Close issue after no response.
If you want reopen, anytime you can reopen.
