### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by yirmisekiz** [ParkSangGwon/TedBottomPicker#105]
my app run in android 5.0  . no problem
when I run in android 7.0  phone  I take error 

there is no error code but Mainactiviy.java:116   

it's too  " create();"

 thanks all somthing

**Comment by ParkSangGwon** [comment]
@yirmisekiz You have to check your permission.
Read this.
https://github.com/ParkSangGwon/TedBottomPicker#1-check-permission
