### ISSUE TITLE
Exception on Permission change from settings  when you already given permission 

### ISSUE THREAD

**Issue by abhi385** [ParkSangGwon/TedBottomPicker#109]
Exception on Permission change from settings  when you already given permission and your ted picker dialog was open .when we come back from settings screen after changing permission due to android kill the process.........i get null pointer exception

**Comment by ParkSangGwon** [comment]
@abhi385 
Yes, you are right.
When permission change by setting, this dialog recreate and occur crash
I update version v2.0.1
You can not crash free!!
