### ISSUE TITLE
MainActivity showUriList에서 removeImage()를 호출 하고 싶습니다.

### ISSUE THREAD

**Issue by kht777** [ParkSangGwon/TedBottomPicker#120]
안녕하세요?
사용하다가 사진을 모두 선택한후에 done를 누르면
선택된 이미지를 모두 선택해제 하고 selected_photos_container에서도 제거하기 위해
removeImage()를 호출 하고 싶습니다.
MainActivity에서 어떻게 호출하면 될까요?
답변 부탁드립니다~

 private void showUriList(List<Uri> uriList) {
        for (Uri uri : uriList) {
            removeImage(uri);
        }
 }

**Comment by ParkSangGwon** [comment]
@kht777 
선택된 이미지는 `.setSelectedUriList(selectedUriList)`를 통해서 전달됩니다.
선택된 이미지가 없는 상태로 다시 띄우고 싶으신 경우에는 해당 함수를 호출하지 않으면 됩니다.
혹은 selectedUriList의 데이터를 빈값으로 넘기면 됩니다.
