### ISSUE TITLE
오타 수정

### ISSUE THREAD

**Issue by dlqkfzlr** [ParkSangGwon/TedBottomPicker#136]
Readme.md 파일에서 
사소한 오타가 발견되어서 알려드립니다. :)
(Highlight된 부분)
![image](https://user-images.githubusercontent.com/44568146/103421842-c8970f80-4be1-11eb-8fd5-94f2b23365c4.png)

**Comment by ParkSangGwon** [comment]
감사합니다. 정정되었습니다.
