### ISSUE TITLE
Specify infinity maxCount for picker

### ISSUE THREAD

**Issue by programmerr47** [ParkSangGwon/TedBottomPicker#14]
Currently, as I understood correctly, we can specify max count of photos through TedBottomPicker.Builder.maxCount. But I for example want to show all images from gallery. 

Now I can write something like: 
```java 
builder.setMaxCount(Integer.MAX_VALUE)
```

But it looks like workaround.

I want to be able to write something like:
```java 
builder.noLimit()
```
or even better have unlimited list as default behavior and possibility to limit it through: 
```java 
builder.limit(25)
```

Thank you.

**Comment by ParkSangGwon** [comment]
@programmerr47 
That's good idea.
I will consider about function name
