### ISSUE TITLE
Orientation Bitmap

### ISSUE THREAD

**Issue by mslarco** [ParkSangGwon/TedBottomPicker#16]
Good work the library is excellent, but I need to print the photograph and get the exift data of the URI.

It returns me empty when I want to get the orientation of the photo. :(

Here. 

 tedBottomPicker = new TedBottomPicker.Builder(ActivityVisitaFotografias.this)

                .setOnImageSelectedListener(new TedBottomPicker.OnImageSelectedListener() {
                    @Override
                    public void onImageSelected(Uri uri) {
                        Bitmap bitmap=null;
                        try {
                             bitmap = MediaStore.Images.Media.getBitmap(getApplicationContext().getContentResolver(), uri);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        if(bitmap!=null)
                            imageView.setImageBitmap(bitmap);

                    }
                })

**Comment by ParkSangGwon** [comment]
@mslarco Did you print log `Uri`?
Let me know your `Uri` address

**Comment by ParkSangGwon** [comment]
@mslarco Did not answer. I will close.
