### ISSUE TITLE
image is not selected if it was picked from gallery or using camera app

### ISSUE THREAD

**Issue by revic1993** [ParkSangGwon/TedBottomPicker#18]
While using this library, i got to know that the image which i select from gallery, will not selecting as the final result, it just stuck at the same bottompicker screen.
When tried to click a pic using the camera button provided in bottompicker, it isn't saving the photo i just clicked, (had all the required permissions), do check and reply soon

**Comment by miri-rasoul** [comment]
you use public void onActivityResult(int requestCode, int resultCode, Intent data) {} in activity?

**Comment by revic1993** [comment]
@miri-rasoul yes n still it isn't selecting any image

**Comment by miri-rasoul** [comment]
in TedBottomPicker.class , he is use onActivityResult and u Override again

**Comment by revic1993** [comment]
@miri-rasoul Ok will check it out. Thanks

**Comment by ParkSangGwon** [comment]
@revic1993 Did you solve this problem?
If you have still problem, show me your code.

**Comment by gowrav** [comment]
Use super method call in your activity like this 
 @Override
    protected void onActivityResult(int requestCode, int resultCode, final Intent data) {
        super.onActivityResult(requestCode,resultCode,data);

// Your Activity Result Managment Code here

}

**Comment by ParkSangGwon** [comment]
Close.
Because no response.
