### ISSUE TITLE
NullPointerException on rotation when the picker is open

### ISSUE THREAD

**Issue by blunden** [ParkSangGwon/TedBottomPicker#19]
Is the library supposed to handle rotation itself or am I supposed to hide it somehow before the rotation takes place? At the moment I can't think of a simple way to solve it in my app (but it's 3 am after all).

AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{CENSORED/CENSORED.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'int gun0912.tedbottompicker.TedBottomPicker$Builder.peekHeight' on a null object reference

**Comment by ParkSangGwon** [comment]
@blunden Do you support rotation mode?

**Comment by blunden** [comment]
I support rotation in my app if that's what you mean. I don't save anything related to your picker in onSaveInstanceState though because I could see anything obvious to store there. I am using your image picker within another Fragment and I suppose that might affect as they don't get recreated in the same way as Activities on rotation.

Is rotation working in the apps where you use this?

**Comment by ParkSangGwon** [comment]
@blunden I fixed this problem now. you can use correct version at v1.0.6

**Comment by blunden** [comment]
So you have verified that rotation now works without crashing? :) It's a little hard to read the commit history as you bundle changes per version instead of separate commits.

I'll give this a try. I'll have to build it myself though as I need the Nougat support patch found among the pull requests. Please look into merging that as I'm sure there are many people wanting to support the latest Android versions.
