### ISSUE TITLE
Dialog显示时，status bar颜色会发生改变

### ISSUE THREAD

**Issue by Callous123** [ParkSangGwon/TedBottomPicker#3]
选择器弹出后，status bar会发生变化，变成黑色。关闭后，恢复蓝色

**Comment by ParkSangGwon** [comment]
@Callous123 
Sorry, I am not chinese.
Can you tell me in english?

**Comment by namezhouyu** [comment]
let me translate this question：
status bar will change to black when the TedBottomPicker instance executting method “show”，and came to blue when the instance dismiss

**Comment by ParkSangGwon** [comment]
No answer
