### ISSUE TITLE
How open tedbottom with slected image from uri

### ISSUE THREAD

**Issue by enggazzar** [ParkSangGwon/TedBottomPicker#30]

**Comment by ParkSangGwon** [comment]
@enggazzar 
You can Readme.md
https://github.com/ParkSangGwon/TedBottomPicker/blob/master/README.md

**Comment by enggazzar** [comment]
in TedPicker i can use      
Intent intent  = new Intent(this, ImagePickerActivity.class);
        startActivityForResult(intent,INTENT_REQUEST_GET_IMAGES);
and send uri  but idonot know how use this here

**Comment by ParkSangGwon** [comment]
@enggazzar What did you mean?
Did you read how to use `TedBottomPicker`?

**Comment by enggazzar** [comment]
yes but i canot fount function that ineed

**Comment by ParkSangGwon** [comment]
@enggazzar Ah...Did you mean after select again situation?
When user re-open tedbottompicker, you want to show them already selected picture.
Right?

**Comment by ParkSangGwon** [comment]
@enggazzar Now you can use `selectedUriList()` function at v1.0.11

**Comment by enggazzar** [comment]
thanks alot
