### ISSUE TITLE
Permission Denial error

### ISSUE THREAD

**Issue by majidkabir** [ParkSangGwon/TedBottomPicker#31]
This error occurred in version 1.0.9
FATAL EXCEPTION: main
java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{42997758 569:com.sec.android.app.camera/u0a10079} (pid=569, uid=10079) that is not exported from uid 10163
I google this error and found this link https://medium.com/@a1cooke/using-v4-support-library-fileprovider-and-camera-intent-a45f76879d61#.34hcs7dml

I read this page and based on that I think you should add below code to startCameraIntent method

Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);

List<ResolveInfo> resolvedIntentActivities = context.getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);

for (ResolveInfo resolvedIntentInfo : resolvedIntentActivities) {
    String packageName = resolvedIntentInfo.activityInfo.packageName;

    context.grantUriPermission(packageName, fileUri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
}

I think it happened just on multi image selecting!

**Comment by majidkabir** [comment]
I use below code and it's worked. Please check this and update your lib. thanks
```
    private void startCameraIntent() {
        Intent cameraInent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        if (cameraInent.resolveActivity(getActivity().getPackageManager()) == null) {
            errorMessage("This Application do not have Camera Application");
            return;
        }

        File imageFile = getImageFile();
        Uri photoURI = FileProvider.getUriForFile(getContext(), getContext().getApplicationContext().getPackageName() + ".provider", imageFile);

        List<ResolveInfo> resolvedIntentActivities = getContext().getPackageManager().queryIntentActivities(cameraInent, PackageManager.MATCH_DEFAULT_ONLY);
        for (ResolveInfo resolvedIntentInfo : resolvedIntentActivities) {
            String packageName = resolvedIntentInfo.activityInfo.packageName;
            getContext().grantUriPermission(packageName, photoURI, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        }

        cameraInent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
        startActivityForResult(cameraInent, REQ_CODE_CAMERA);

    }
```

**Comment by ParkSangGwon** [comment]
@majidkabir Thanks your pull request

**Comment by iammert** [comment]
@majidkabir You are lifesaver! thanks for PR.

**Comment by vishalenrique** [comment]
can anyone please explain the code?
```
 List<ResolveInfo> resolvedIntentActivities = getContext().getPackageManager().queryIntentActivities(cameraInent, PackageManager.MATCH_DEFAULT_ONLY);
        for (ResolveInfo resolvedIntentInfo : resolvedIntentActivities) {
            String packageName = resolvedIntentInfo.activityInfo.packageName;
            getContext().grantUriPermission(packageName, photoURI, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        }
```
