### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by j-mateo** [ParkSangGwon/TedBottomPicker#36]
LeakCanary detected a memory leak. Tracking it down, I found that there's a static variable for the builder at [TedBottomPicker.java:16](https://github.com/ParkSangGwon/TedBottomPicker/blob/master/tedbottompicker/src/main/java/gun0912/tedbottompicker/TedBottomPicker.java#L61) and the builder has a reference to the context [TedBottomPicker.java:553](https://github.com/ParkSangGwon/TedBottomPicker/blob/master/tedbottompicker/src/main/java/gun0912/tedbottompicker/TedBottomPicker.java#L553)

Is there a reason for keeping a static instance of the builder?

**Comment by prophet173** [comment]
changed to public myself and it has zero problem, so...

**Comment by j-mateo** [comment]
Fixed [here](https://github.com/ParkSangGwon/TedBottomPicker/commit/c4f0907dfad838be6cc019e9cdeafda28022b5c0)
