### ISSUE TITLE
Camera Option is not working 

### ISSUE THREAD

**Issue by veeranath** [ParkSangGwon/TedBottomPicker#38]
Hi... i am getting by this exception **Attempt to read from field 'int gun0912.tedbottompicker.TedBottomPicker$Builder.peekHeight' on a null object reference** when i select the camera option in the Android 6.0.1 Asus Zenfone 2 laser and also using i the portrait mode

**Comment by ParkSangGwon** [comment]
@veeranath Can you show me your code?

**Comment by iammert** [comment]
Same here. Looks like builder is null on setupDialog method. Here is the stacktrace output.

> Attempt to read from field 'int gun0912.tedbottompicker.TedBottomPicker$Builder.peekHeight' on a null object reference

Here is my code. I need an urgent solution. Thanks.
```
 TedBottomPicker bottomSheetDialogFragment = new TedBottomPicker.Builder(AddNoteActivity.this)
                                .setOnImageSelectedListener(uri -> viewModel.startCropActivity(uri))
                                .setPeekHeight(getResources().getDisplayMetrics().heightPixels / 2)
                                .create();
                        bottomSheetDialogFragment.show(getSupportFragmentManager());
```

**Comment by iammert** [comment]
@ParkSangGwon It is crashing only some 4.4 samsung devices. Do you have any solution about that problem?

**Comment by ParkSangGwon** [comment]
@veeranath @iammert Did you test sample project?
Download `TedBottomPickerDemo`and test.
And tell me sample is ok or not

**Comment by iammert** [comment]
I did not test it actually. But my project is integrated with fabric. So I can not reproduce that error in my devices but that error occurs on some of my users.

**Comment by ParkSangGwon** [comment]
@iammert Now I add code `null check`. You can use this code at v1.0.11
