### ISSUE TITLE
How Open Only Camera without Gallary

### ISSUE THREAD

**Issue by enggazzar** [ParkSangGwon/TedBottomPicker#48]

**Comment by enggazzar** [comment]
Take a picture by camera(using MediaStore.ACTION_IMAGE_CAPTURE intent)
how set MediaStore.ACTION_IMAGE_CAPTURE

**Comment by ParkSangGwon** [comment]
@enggazzar If you don't want gallery tile, you can call `showGalleryTile(false)`
