### ISSUE TITLE
video picker

### ISSUE THREAD

**Issue by omeed12** [ParkSangGwon/TedBottomPicker#52]
Is it possible to pick videos too?

**Comment by ParkSangGwon** [comment]
Hm... I will consider about it.
If many people need this feature, I will add.
Or you can make and pullrequest.

**Comment by g5122053** [comment]
+1 this feature

**Comment by akashk1992** [comment]
@ParkSangGwon 
+1

**Comment by ParkSangGwon** [comment]
@omeed12 @g5122053 @hardikamal @akashk1992 
Now you can load video using `showVideoMedia()` at v2.1.0
