### ISSUE TITLE
TedBottomPicker not working with uCrop library

### ISSUE THREAD

**Issue by devdigitalappteam** [ParkSangGwon/TedBottomPicker#53]
My requirement is need to select the photo from camera or photos and crop with ratio of 16:9.
So I user TedBottomPicker for the image selection part and for crop I used uCrop lib but face issue that picket conflict with the onActivityResult and unable to select image from camera as well photos.

**Comment by ParkSangGwon** [comment]
@devdigitalappteam If you got error mesage, show me error message.
I will try solve your problem

**Comment by ParkSangGwon** [comment]
No answer, close
