### ISSUE TITLE
declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.studio-1/base.apk

### ISSUE THREAD

**Issue by sudikrt** [ParkSangGwon/TedBottomPicker#54]
I have used Glide in my base app but when i call TedBottom picker it gives this error

**Comment by sprengerst** [comment]
I think the problem is the glide version. This library uses 3.6.1

**Comment by ParkSangGwon** [comment]
Yes. This Glide's library version is 3.6.1.
If you use 4.x version, you have to `setImageProvider()` with `Builder`.
You can load your image loading library.

**Comment by idedalusse** [comment]
Hi gay, How can i upload multiples images to firebase using TedBottomPicker?
