### ISSUE TITLE
Problem with landscape mode.

### ISSUE THREAD

**Issue by Silverpp** [ParkSangGwon/TedBottomPicker#56]
Hi.
Appreciate for sharing awesome source code.
This library really useful and efficiency to me.

But I noticed that has problem with landscape mode screen.
First, when it start in landscape mode shows only 'Select image' title bar.
Second, photo image tile size is too big to show in landscape mode.

In my opinion this behavior looks something strange.
Tested version is '1.0.12'

Thanks.
-------------------------------------------------------------

안녕하세요.
먼저 좋은 소스코드 공유해주셔서 너무 감사하구요...
제 프로젝트에 너무 필요한 기능이라 감동하고 있습니다. ^^

그런데 가로 모드에서는 조금 이상한 동작을 하고 있는듯 보입니다.
먼저 처음 Picker를 실행하면 타이틀 바에 사진 선택 바만 살짝 보입니다.
거기에 바를 올려보면 이미지 타일이 가로모드에서는 조금 크게 보입니다.

이상의 동작이 제 생각엔 조금 이상하게 보입니만 수정 계획이 있으실지 문의 합니다.
테스트 버전은 '1.0.12'입니다.

감사합니다.

**Comment by ParkSangGwon** [comment]
@Silverpp Show me your sample code
I will try test using your code

**Comment by Silverpp** [comment]
Thanks for your quick reply :)
Please refer as below.

If you want whole code includes layout resources, don't know how send you because it so many lines ;(

------------------------------------------------------------------
   View.OnClickListener mAddPhotoListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            SLog.d(TAG, "mAddPhotoListener");
            TedBottomPicker tedBottomPicker = new TedBottomPicker.Builder(getActivity())
                .setOnImageSelectedListener(imageSelectedListener)
                .create();
            tedBottomPicker.show(getActivity().getSupportFragmentManager());
        }
    };

    TedBottomPicker.OnImageSelectedListener imageSelectedListener
            = new TedBottomPicker.OnImageSelectedListener() {
        @Override
        public void onImageSelected(Uri uri) {
            if(uri != null) {
                mTestingManager.saveStudentPhoto(
                        mStudentIndex,
                        uri,
                        new TestingDataManager.TestingDataListener() {
                            @Override
                            public void saveDoneListener(int result, String id, String path) {
                                SLog.d(TAG, "Image saved code = " + result);
                                if(result == TestingDataManager.TESTING_DATA_COMMON_OK) {
                                    Student student =
                                            mTestingManager.getStudent(mStudentIndex);
                                    addPhotoViewList(path);
                                    student.addPhotoFile(path);
                                } else {
                                    Util.showCustomToast(getActivity(),
                                            R.string.label_toast_save_photo);
                                }
                            }

                            @Override
                            public void createDoneListener(int result, String id) {

                            }

                            @Override
                            public void loadDoneListener(int result, String id) {

                            }
                        });
            } else {
                Util.showOkDialog(
                        getActivity(),
                        getString(R.string.label_title_error),
                        getString(R.string.label_camera_capture_image_failed));
            }
        }
    };

-----------------------------------------------------------------------------------
First issue image
![device-2017-08-02-185457](https://user-images.githubusercontent.com/27726265/28868368-393e6fb8-77b4-11e7-8728-c7033b9b263f.png)

Second issue image
![device-2017-08-02-185521](https://user-images.githubusercontent.com/27726265/28868391-50777ee0-77b4-11e7-9668-537ad167bfbb.png)

**Comment by ParkSangGwon** [comment]
@Silverpp 
답변이 늦었습니다.
`.setPeekHeight()`로 원하는 초기 높이를 지정해주세요
샘플코드를 보시면 사용방법을 확인해보실 수 있습니다.
