### ISSUE TITLE
cannot get uri when select camera icon or gallery icon

### ISSUE THREAD

**Issue by rlawlwoong** [ParkSangGwon/TedBottomPicker#57]
```
 //Image Upload
                TedBottomPicker tedBottomPicker = new TedBottomPicker.Builder(MainActivity.this)
                        .setOnImageSelectedListener(new TedBottomPicker.OnImageSelectedListener() {
                            @Override
                            public void onImageSelected(Uri uri) {
                                // here is selected uri
                                Log.e("CAMERA",uri.toString());
                       
                            }
                        })

                        .create();
               
                tedBottomPicker.show(getSupportFragmentManager());
```

 I try to get Uri from onImageSelected, but I can not get Uri when I select image from touch camera or gallery icon. I just can get Uri when I touch other bottom images.
Could you let me know how to get Uri when I touch camera or gallery icon?
Thanks :)

onImageSelected를 통해서 Uri를 가져오고 싶은데, 카메라 버튼이나 갤러리 버튼을 통해서 사진을 선택할 경우 Uri를 가져오지 못하고, 밑에 뜨는 이미지를 선택할 때는 Uri를 가져옵니다. 혹시 카메라버튼이나 갤러리 버튼을 통해 선택한 사진의 Uri를 가져오려면 어떻게 구현하면 될까요?

감사합니다.

**Comment by rlawlwoong** [comment]
And I'm using  'gun0912.ted:tedbottompicker:1.0.12'

**Comment by ParkSangGwon** [comment]
@rlawlwoong 권한획득은 하셨나요?

**Comment by ParkSangGwon** [comment]
No answer close.
