### ISSUE TITLE
Allow setSpacing() to impact on edges too

### ISSUE THREAD

**Issue by Jeevuz** [ParkSangGwon/TedBottomPicker#58]
Hi! Nice library!

It will be really nice to allow setSpacing to add space from the edges too. 

It seems to be not hard, because this feature already in your code base:
```java
rc_gallery.addItemDecoration(new GridSpacingItemDecoration(gridLayoutManager.getSpanCount(), builder.spacing, false));
```

Will be great if you can add parameter to change this false to true in the builder. Maybe right in the setSpacing() method.

**Comment by ParkSangGwon** [comment]
@Jeevuz 
Okay, Good idea.
I will add this function

**Comment by ParkSangGwon** [comment]
@Jeevuz 
Do you mean edge spacing enable/disable function?
I will add that function future

**Comment by Jeevuz** [comment]
Yes, some parameter to enable/disable it in the setSpacing(), or separate method.

**Comment by ParkSangGwon** [comment]
Ok. I will add function  for you

**Comment by ParkSangGwon** [comment]
This function added at `v1.2.0`
