### ISSUE TITLE
Allow videos to be selected as well?

### ISSUE THREAD

**Issue by WesleyLemke** [ParkSangGwon/TedBottomPicker#60]
Is there an easy way to allow videos to be selected as well?

**Comment by ParkSangGwon** [comment]
This library doesn't support video.
I will add function for you.
Please wait

**Comment by yankelandroid** [comment]
Please me too I need video thanks

**Comment by yankelandroid** [comment]
so can you please do for video also ?

**Comment by yankelandroid** [comment]
its urgent

**Comment by ParkSangGwon** [comment]
I will add
