### ISSUE TITLE
Add support for Glider 4.0

### ISSUE THREAD

**Issue by mambisi** [ParkSangGwon/TedBottomPicker#67]

**Comment by ekohere** [comment]
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager'

**Comment by theGnartist** [comment]
https://github.com/ParkSangGwon/TedBottomPicker/pull/63
there was a pull request recently closed which contains the correct Glide 4.0 implementation.
I've pull those changes into my own fork to use in a project I'm working on.  If you want to used Glide 4.0 feel free to use my fork via jitpack 
com.github.theGnartist:TedBottomPicker:2.0.0-b1

**Comment by ParkSangGwon** [comment]
Yes I know.
But still many developer use 3.x version.
If I update version, under 4.x version user can not use this library.
So I provide `ImageProvider`.
You can use `setImageProvider()`
