### ISSUE TITLE
Need Help Developing MultiSelection feature?

### ISSUE THREAD

**Issue by brotoo25** [ParkSangGwon/TedBottomPicker#7]
Just wondering if you're already working in this feature if so, would you commit your working in progress? But if you are not I'll just keep working on my own implementation.

**Comment by ParkSangGwon** [comment]
If someone want multi-selection, I will add function.
Theseday I have little busy.
Be patient plz.

**Comment by pkozlovskiy** [comment]
Add, please,

**Comment by ParkSangGwon** [comment]
@brotoo25 @pkozlovskiy You can select multi image at 1.0.5 version
