### ISSUE TITLE
add duration max video 

### ISSUE THREAD

**Issue by AX-NICOLAS** [ParkSangGwon/TedBottomPicker#72]
@ParkSangGwon 

Hello,

He isn't possible to create a pull request so I upload the code to do this.

Can you add possibility of set duration max when it's a video ? 

Thanks,

`      if (builder.mediaType == Builder.MediaType.IMAGE) {
            cameraInent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
            mediaFile = getImageFile();
        } else {
            cameraInent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
            if(null != builder.durationLimitVideo){
                cameraInent.putExtra("android.intent.extra.durationLimit", builder.durationLimitVideo);
            }
            mediaFile = getVideoFile();
        }
`

`
       public Builder setDurationLimitVideo(long milliSecond){
            this.durationLimitVideo = milliSecond;
            return this;
        }
`

`
         in Builder

        public String completeButtonText;
        public String emptySelectionText;
        public String selectMaxCountErrorText;
        public String selectMinCountErrorText;

        public Long durationLimitVideo;

        public @MediaType
        int mediaType = MediaType.IMAGE;
`

**Comment by AX-NICOLAS** [comment]
Do you plan to update the library or not? Otherwise I fork...

**Comment by ParkSangGwon** [comment]
@AX-NICOLAS 
Thanks for your suggestion.
Anytime you can pull request to this project.
I waiting your pull request and review.

**Comment by anonym2** [comment]
So he made it  AX-NICOLAS ?
