### ISSUE TITLE
Update Glide dependency

### ISSUE THREAD

**Issue by bpappin** [ParkSangGwon/TedBottomPicker#77]
The Glide dependency is at 3.6.1 and the current release is at 4.5.0, which is a breaking change.
Update the library to accept current versions of Glide, or remove the dependency.

**Comment by bpappin** [comment]
This is now done in pull request #82
You can close this issue once that pull request has been merged.

**Comment by ParkSangGwon** [comment]
This issue's comment can replied at #82 
Thanks @bpappin
