### ISSUE TITLE
dismiss causes IllegalStateException

### ISSUE THREAD

**Issue by akichusell** [ParkSangGwon/TedBottomPicker#8]
when camera (by MediaStore.ACTION_IMAGE_CAPTURE intent) or gallery (by Intent.ACTION_PICK intent) is used, TedBottomPicker calls "dismiss()" after OnImageSelectedListener's onImageSelected() in onActivityResult().

but, in this case, dismiss() is likely to occur exceptions. (in detail, IllegalStateException:Can not perform this action after onSaveInstanceState)

for example, (in my case) NestedFragment (I mean, fragment has another fragment as child) calls TedBottomPicker. and I choose in onImageSelected() start other Activity. 

in this case IllegalStateException occurs.

how do you think about changing dismiss() to dismissAllowingStateLoss()?

**Comment by ParkSangGwon** [comment]
Fixed at 1.0.4 version
