### ISSUE TITLE
No image selected from Galary or using Camera

### ISSUE THREAD

**Issue by MoaazElneshawy** [ParkSangGwon/TedBottomPicker#84]
When I try to select the image from Galary or using Camera no thing happens 

Here's my code ... 
TedBottomPicker bottomSheetDialogFragment = new TedBottomPicker.Builder(MerchantSignUp.this)
                        .setOnImageSelectedListener(new TedBottomPicker.OnImageSelectedListener() {
                            @Override
                            public void onImageSelected(Uri uri) {

                                String filePath = DocumentHelper.getPath(MerchantSignUp.this, uri);
                                //Safety check to prevent null pointer exception
                                if (filePath == null || filePath.isEmpty()) {
                        
                                    return;
                                }

                                String compressFilePath = ImageHelper.compressImage(filePath);
                                if (compressFilePath == null || compressFilePath.isEmpty()) {
                           
                                    return;
                                } else {
                                    // image is selected
                                }
                            }
                        })
                        .setPeekHeight(getResources().getDisplayMetrics().heightPixels / 2)
                        .create();

                bottomSheetDialogFragment.show(getSupportFragmentManager());

**Comment by ParkSangGwon** [comment]
@MoaazElneshawy Did you got permission?

**Comment by MoaazElneshawy** [comment]
Sure I did , the crash happened on Samsung Devices because their Camera rotation , So , there was a solution in another reported issue about the same here , android:configChanges="orientation|keyboardHidden|screenSize" , and this solve the problem

**Comment by MoaazElneshawy** [comment]
I've override the onActivityResult method , and the captured photo by the camera saved rotated 
the crash now happens only when I rotated the camera itself to take a photo

**Comment by IsaEs** [comment]
if you have to override the onActivityResult you should call super method in onActivityResult. I had the same issue and this line solved my problem.
`super.onActivityResult(requestCode, resultCode, data) `

**Comment by ParkSangGwon** [comment]
This issue solved at `v1.2.0`.
I use `TedRxOnActivityResult` instead of `startActivityForResult()`.
https://github.com/ParkSangGwon/TedRxOnActivityResult
